### ISSUE TITLE
NullReferenceException in multiplayer when farmhand is at Elliot's 10-heart event

### ISSUE THREAD

**Issue by pingzing** [mishagp/PauseInMultiplayer#6]
Hi there!

Was using this the other night in multiplayer with `Any cutscene pauses` enabled. I was the host, and my farmhand triggered the Elliot 10 heart event. During the event, I continuously received the following error:

```csharp
NullReferenceException: Object reference not set to an instance of an object.
   at PauseInMultiplayer.PauseInMultiplayer.GameLoop_UpdateTicking(Object sender, UpdateTickingEventArgs e) in /Users/misha/PauseInMultiplayer/PauseInMultiplayer/PauseInMultiplayer.cs:line 538
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

So, at a guess, `.characters` was `null` for the `location` that my farmhand was in?

This was with:
Stardew Valley:  v1.6.3
SMAPI: v4.0.3
Mod: v1.8.0

**Comment by mishahawthorn** [comment]
Should be resolved in #16, please give the latest update a try and feel free to re-open if it's still not working!
