### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by woahs** [mishagp/PauseInMultiplayer#7]
Getting the following Error Exception in SMAPI logs:

```
This mod failed in the GameLoop.UpdateTicking event. Technical details: 
NullReferenceException: Object reference not set to an instance of an object.
   at PauseInMultiplayer.PauseInMultiplayer.GameLoop_UpdateTicking(Object sender, UpdateTickingEventArgs e) in /Users/misha/PauseInMultiplayer/PauseInMultiplayer/PauseInMultiplayer.cs:line 538
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```
Same exception repeated 484 times. Did not observe any strange behavior in game yet.

**Comment by mishahawthorn** [comment]
Should be resolved in #16, please give the latest update a try and feel free to re-open if it's still not working!
